### ISSUE TITLE
[RFC] Moving from `always` trailing commas to `always-multiline`

### ISSUE THREAD

**Issue by malparty** [nimblehq/eslint-config-nimble#13]
## RFC

It seems like I went a little too fast on the previous change (confused by prettier config "all").
We wanted to include end-of-line trailing commas at the end of multi-line statements (cf the [compass update here](https://github.com/nimblehq/compass/pull/767)). 

But we did not mention much about the single-line statements.

So let's now vote for the single line statements :) 

1. Keep `always`
  ```javascript
  export const supportedLanguages = ['en', 'fr', ]; // Enforced trailing commas here
  export const supportedLanguages = [
    'en',
    'fr', // Enforced
  ];
  ```

2. Change to `only-multiline`
  ```javascript
  export const supportedLanguages = ['en', 'fr', ]; 
  export const supportedLanguages = ['en', 'fr']; // Both format allowed for single-line statement
  export const supportedLanguages = [
    'en',
    'fr', // Enforced trailing commas here
  ];
  ```

3. Change to `always-multiline`
  ```javascript
  export const supportedLanguages = ['en', 'fr']; // Enforced no trailing commas here
  export const supportedLanguages = [
    'en',
    'fr', // Enforced trailing commas here
  ];
  ```

More info [here](https://eslint.org/docs/rules/comma-dangle).

> ℹ️ Option 1 and 2 exposed to a **conflict** with another rule `, ]` (no space allowed before `]`. If such an option is voted, we will need to find a solution to solve that.

## Poll

_Pool deadline: 4 november at 2pm (Thai/Vietnam)._

[![](https://api.gh-polls.com/poll/01FKN7R057H1VACPRBWHK7EBW6/1.%20Keep%20%60always%60)](https://api.gh-polls.com/poll/01FKN7R057H1VACPRBWHK7EBW6/1.%20Keep%20%60always%60/vote)
[![](https://api.gh-polls.com/poll/01FKN7R057H1VACPRBWHK7EBW6/2.%20Change%20to%20%60only-multiline%60)](https://api.gh-polls.com/poll/01FKN7R057H1VACPRBWHK7EBW6/2.%20Change%20to%20%60only-multiline%60/vote)
[![](https://api.gh-polls.com/poll/01FKN7R057H1VACPRBWHK7EBW6/3.%20Change%20to%20%60always-multiline%60)](https://api.gh-polls.com/poll/01FKN7R057H1VACPRBWHK7EBW6/3.%20Change%20to%20%60always-multiline%60/vote)

**Comment by hoangmirs** [comment]
It was resolved in https://github.com/nimblehq/eslint-config-nimble/pull/14
