### ISSUE TITLE
Add the project's maintainers info

### ISSUE THREAD

**Issue by hoangmirs** [nimblehq/eslint-config-nimble#21]
## Why

Add CODEOWNERS file:
- We can know the maintainers of this project
- To make it consistent with other repositories

## Who Benefits?

Developers who contribute to this project

**Comment by hoangmirs** [comment]
@olivierobert Would you mind adding this?

**Comment by olivierobert** [comment]
We could make @carryall the team lead for all JS related projects for now 🦢  You can go ahead creating such file too.
